### ISSUE TITLE
Refactor to use @dillonkearns elm-graphql

### ISSUE THREAD

**Issue by kutyel** [kutyel/mu-graphql-example-elm#1]
https://github.com/dillonkearns/elm-graphql

We are all on board on the idea of sharing the schemas and types between the frontend and the backend 🎉 

But for some reason I could not easily make this library to work with our `schema.graphql`, need to investigate more! 🤔

**Comment by kutyel** [comment]
cc: @dillonkearns 😉

**Comment by vladimirlogachev** [comment]
I have these two libraries working together in a very primitive setup (work in progress, very early stage, but it works).

https://github.com/VladimirLogachev/library

![image](https://user-images.githubusercontent.com/17773003/95610837-24db0f00-0a8b-11eb-9451-5006664ab24d.png)

**Comment by kutyel** [comment]
This is awesome! Feel free to add a link to your repo in a PR to `mu-haskell`, we'd love to have more community contributions! 🙌

**Comment by vladimirlogachev** [comment]
Sure, when I will deploy it. Now it's not ready yet.
But for now, I can help to fix this elm example.
`mu-haskell` example runs successfully on my machine, and this example too.
I will make a PR tomorrow.
